// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyChnrFQ8WIN3PIFaTFmGPADIXKTuWF1vEI',
    appId: '1:901871260808:web:86afc0fc43a8f4b77dfb3d',
    messagingSenderId: '901871260808',
    projectId: 'edugaite-473d2',
    authDomain: 'edugaite-473d2.firebaseapp.com',
    storageBucket: 'edugaite-473d2.appspot.com',
    measurementId: 'G-KFMSC97LTL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAP0_JjoSGHXfhRNvqVCJfnanGgzJXW9DI',
    appId: '1:901871260808:android:3664155a7cf29e387dfb3d',
    messagingSenderId: '901871260808',
    projectId: 'edugaite-473d2',
    storageBucket: 'edugaite-473d2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBF1VAifMOe4xBd_rxPNhvoX9zDX4JiCkE',
    appId: '1:901871260808:ios:67ec22978f64f8e87dfb3d',
    messagingSenderId: '901871260808',
    projectId: 'edugaite-473d2',
    storageBucket: 'edugaite-473d2.appspot.com',
    iosBundleId: 'com.example.edugaite',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBF1VAifMOe4xBd_rxPNhvoX9zDX4JiCkE',
    appId: '1:901871260808:ios:67ec22978f64f8e87dfb3d',
    messagingSenderId: '901871260808',
    projectId: 'edugaite-473d2',
    storageBucket: 'edugaite-473d2.appspot.com',
    iosBundleId: 'com.example.edugaite',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyChnrFQ8WIN3PIFaTFmGPADIXKTuWF1vEI',
    appId: '1:901871260808:web:79c05bd47f26e4d17dfb3d',
    messagingSenderId: '901871260808',
    projectId: 'edugaite-473d2',
    authDomain: 'edugaite-473d2.firebaseapp.com',
    storageBucket: 'edugaite-473d2.appspot.com',
    measurementId: 'G-8TQ61ELEWT',
  );

}